spring:
  application:
    name: tickets
  datasource:
    url: jdbc:postgresql://localhost:5432/event_ticket
    username: postgres
    password: thanhtuong1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/event-ticket-platform
logging:
  level:
    org:
      springframework:
        security: DEBUG
      keycloak: DEBUG
